"""crear_tablas_iniciales

Revision ID: f3a406deec11
Revises: 
Create Date: 2026-05-24 18:09:00.198990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a406deec11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('compania_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['compania_id'], ['companias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_correo'), 'empleados', ['correo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleados_correo'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_table('companias')
    # ### end Alembic commands ###
